# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3fd90c7847bf3a52ddd232fd5719b7c8379b286a5e0c0b908f9de89367fd65182bb003b9c2639a8ae6df1a986a87ff342516607b2accb628a0200df32db1447c

test:
  secret_key_base: 7510c965522bd73673daec5acdc95f0028d469b0b2866c42e2e6a37f2afda63d5dd7c09ba65efdaaae72b83d610cee314a8e5202e9ab7db4869a05976a991313

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
